### PR TITLE
Add entry for Nifty Digits

### PR DESCRIPTION
**Pull request by iwootten**
Add entry for Nifty Digits

### CODE REVIEW

**Comment by stephlocke** [comment]
@iwootten Your image needs to be added into the images directory and referenced unfortunately due to the limitation of the theme expecting only relative files.

**Comment by iwootten** [comment]
No probs, thought so.

**Comment by iwootten** [comment]
In the netlify preview this now appears a bit broken, is something up with the theme?

**Comment by stephlocke** [comment]
Merged in, looks good on master. I didn't have a leading / on mine which I think ws causing some issues in the PR.

**Pull request merged**
